# Podman Pod definition for Email MCP Gateway
#
# Architecture:
#   Agents (SSE :24268) ←→ mcp-proxy ←→ node dist/main.js stdio (email-mcp)
#
# email-mcp is READ+DRAFT ONLY — send/reply/forward permanently removed.
# See ADR-006 and mcp/email-mcp/src/tools/send.tool.ts.
#
# Config is NOT baked into the image. It lives on the host at:
#   /ai/mcp-email/config/config.toml   (IMAP/SMTP accounts, credentials)
#   /ai/mcp-email/logs/                (log output)
#
# Config volume mount:
#   Host:       /ai/mcp-email/config/
#   Container:  /etc/mcp-email/email-mcp/   (read-only)
#   Why:        XDG_CONFIG_HOME=/etc/mcp-email, so email-mcp reads
#               /etc/mcp-email/email-mcp/config.toml
#
# Before starting:
#   mkdir -p /ai/mcp-email/config /ai/mcp-email/logs
#   cp mcp/email-mcp/config/config.toml.template /ai/mcp-email/config/config.toml
#   # Edit /ai/mcp-email/config/config.toml with real IMAP credentials
#
# Usage:
#   cd mcp/email-mcp
#   podman build -t localhost/mcp-gateway-email:latest -f containers/Containerfile .
#   podman play kube containers/pod.yaml
#   podman pod ps
#   podman pod stop mcp-email
#   podman play kube --down containers/pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: mcp-email
  labels:
    app: mcp-gateway
    domain: email
spec:
  hostNetwork: false

  containers:

  # Single container: mcp-proxy (SSE) → email-mcp (stdio)
  - name: gateway
    image: localhost/mcp-gateway-email:latest

    ports:
    - containerPort: 8000
      hostPort: 24268
      protocol: TCP

    env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "8000"
    - name: LOG_LEVEL
      value: "INFO"
    # XDG_CONFIG_HOME is baked into the image but can be overridden here
    - name: XDG_CONFIG_HOME
      value: "/etc/mcp-email"

    volumeMounts:
    # Config volume — host /ai/mcp-email/config/ → /etc/mcp-email/email-mcp/ (read-only)
    # Contains: config.toml (accounts, credentials — NOT committed to git)
    - name: mcp-email-config
      mountPath: /etc/mcp-email/email-mcp
      readOnly: true

    # Logs volume — host /ai/mcp-email/logs/ → /var/log/mcp-email/
    - name: mcp-email-logs
      mountPath: /var/log/mcp-email

    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "1000m"

    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL

  volumes:
  # Config volume — /ai/mcp-email/config/ on host (read-only secrets)
  # Contains config.toml with IMAP account credentials
  - name: mcp-email-config
    hostPath:
      path: /ai/mcp-email/config
      type: DirectoryOrCreate

  # Logs volume — /ai/mcp-email/logs/ on host
  - name: mcp-email-logs
    hostPath:
      path: /ai/mcp-email/logs
      type: DirectoryOrCreate

  restartPolicy: Always
